name: Build with Electron Forge (CI Pre-release)

on:
  push:
    branches:
      - "**"

jobs:
  linux:
    name: Linux (deb/rpm/flatpak)
    runs-on: ubuntu-24.04
    outputs:
      artifact-paths: ${{ steps.collect.outputs.paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install system deps for deb/rpm/flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            dpkg-dev debhelper fakeroot \
            rpm rpm2cpio cpio bsdtar \
            flatpak flatpak-builder bubblewrap ostree
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.freedesktop.Platform//23.08 org.freedesktop.Sdk//23.08

      - name: Install dependencies
        run: npm ci

      - name: Build (Forge make)
        env:
          DEBUG: electron-forge:*
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-artifacts
          path: |
            out/make/**/*.{deb,rpm,flatpak,zip,tar.gz,tar.xz}
          if-no-files-found: warn

  windows:
    name: Windows (Squirrel)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (Forge make)
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: |
            out/make/**/*.{exe,msi,zip}
          if-no-files-found: warn

  macos:
    name: macOS (zip/dmg if configured)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build (Forge make)
        run: npm run make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-artifacts
          path: |
            out/make/**/*.{dmg,zip}
          if-no-files-found: warn

  prerelease:
    name: Create/Update Pre-release
    needs: [linux, windows, macos]
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist-artifacts

      - name: Generate tag and release name
        id: meta
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          BRANCH="${GITHUB_REF_NAME}"
          RUNID="${GITHUB_RUN_ID}"
          TAG="ci-${BRANCH}-${SHORT_SHA}-${RUNID}"
          NAME="CI Pre-release ${BRANCH} ${SHORT_SHA}"
          echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
          echo "name=${NAME}" >> "$GITHUB_OUTPUT"

      - name: Create or update GitHub pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.tag }}
          name: ${{ steps.meta.outputs.name }}
          prerelease: true
          generate_release_notes: true
          files: |
            dist-artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
